wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32]
    rows: [10, 6, 10, 10, 4, 4, 90]
  refreshInterval: 1
  mods:
    clocks_a:
      colors:
        rows:
          even: "blue"
          odd: "lightblue"
      enabled: true
      locations:
        UTC: "Etc/UTC"
        Toronto: "America/Toronto"
        Vancouver: "America/Vancouver"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "chronological"
      title: ""
      type: "clocks"
    docker:
      title: "DOCKER"
      type: docker
      enabled: true
      labelColor: blue
      position:
        top: 0
        left: 3
        height: 3
        width: 2
      refreshInterval: 1s
    ipinfo:
      title: "IP"
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 0
        left: 1
        height: 1
        width: 2
      refreshInterval: 150
    power:
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      title: " ⚡️"
    uptime:
      title: "UPTIME"
      args: [""]
      cmd: "uptime"
      enabled: true
      position:
        top: 1
        left: 1
        height: 1
        width: 2
      refreshInterval: 30
      type: cmdrunner
