-- init.lua
-- vim: set ts=2 sw=2:
require('xp-bar.plugins.aerial-nvim')
require('xp-bar.plugins.fzf-lua')
require('xp-bar.plugins.vim-tmux-navigator')
require('xp-bar.plugins.startify')
require('xp-bar.plugins.nerdtree')
require('xp-bar.plugins.gitsigns')
require('xp-bar.plugins.vim-test')
require('xp-bar.plugins.vim-easy-align')
require('xp-bar.plugins.goyo')
require('xp-bar.plugins.vim-jsdoc')
require('xp-bar.plugins.vim-zoom')
require('xp-bar.plugins.vim-fugitive')
require('xp-bar.plugins.vim-rooter')
require('xp-bar.plugins.emmet-vim')
require('xp-bar.plugins.commentary')
require('xp-bar.plugins.markdown-preview')
require('xp-bar.plugins.pdv')
