# vim: ft=tmux

# Add truecolor support
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

set -g history-limit 20000
set -g buffer-limit 20
set -sg escape-time 0
set -g display-time 1500
set -g remain-on-exit off
set -g repeat-time 300
setw -g allow-rename off
set -g allow-rename off
setw -g automatic-rename off
setw -g aggressive-resize off
set -g focus-events on

# Change prefix key to C-a, easier to type, same to "screen"
unbind C-b
set -g prefix C-a

# Set parent terminal title to reflect current window in tmux session
set -g set-titles on
set -g set-titles-string "#I:#W"

# Start index of window/pane with 1, because we're humans, not computers
set -g base-index 1
setw -g pane-base-index 1

# Enable mouse support
set -g mouse on

set -g default-command zsh

# === Window monitoring for activity and silence === {{{
# Activity bell and whistles
set -g visual-activity on

# TODO: Does not work as well, check on newer versions
set -g visual-silence on
# }}}

# === Renew environment === {{{

set -g update-environment \
  "DISPLAY\
  SSH_ASKPASS\
  SSH_AUTH_SOCK\
  SSH_AGENT_PID\
  SSH_CONNECTION\
  SSH_TTY\
  WINDOWID\
  XAUTHORITY"

bind '$' run "~/.tmux/renew_env.sh"

# }}}

# === Aliases === {{{
set -s command-alias[10] sync='setw synchronize-panes on'
set -s command-alias[11] nosync='setw synchronize-panes off'
set -s command-alias[99] aliases='show-options command-alias'
# }}}
