# vim: ft=tmux

# === Plugins === {{{

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'xp-bar/tmux-battery-heart-meter'
set -g @plugin 'xp-bar/tmux-roman-pane-number'

# adds snippet for pane switching
set -g @plugin 'christoomey/vim-tmux-navigator'

# last saved environment is automatically restored when tmux is started.
# set -g @continuum-restore 'on'

set -g @resurrect-save 'c-s'
set -g @resurrect-restore 'c-y'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'

TMUX_FZF_LAUNCH_KEY="C-f"
TMUX_FZF_ORDER="session|window|pane|command|keybinding|clipboard"

# Run all plugins' scripts
run '~/.tmux/plugins/tpm/tpm'
# }}}
