# ===================================================
# 
# ▌ ▌   ▛▀▖      ▝▌     ▐                       ▗▀▖
# ▝▞ ▛▀▖▙▄▘▝▀▖▙▀▖▝▞▀▘   ▜▀ ▛▚▀▖▌ ▌▚▗▘  ▞▀▖▞▀▖▛▀▖▐  
# ▞▝▖▙▄▘▌ ▌▞▀▌▌   ▝▀▖ ▗▖▐ ▖▌▐ ▌▌ ▌▗▚ ▗▖▌ ▖▌ ▌▌ ▌▜▀ 
# ▘ ▘▌  ▀▀ ▝▀▘▘   ▀▀  ▝▘ ▀ ▘▝ ▘▝▀▘▘ ▘▝▘▝▀ ▝▀ ▘ ▘▐  
# 
# ===================================================

source-file ~/.config/tmux/general.conf
source-file ~/.config/tmux/ui.conf
source-file ~/.config/tmux/keybindings.conf
source-file ~/.config/tmux/plugins.conf
