#!/bin/zsh

function _in() {
    # required
    [[ -e $HOME/z.sh ]] && source $HOME/z.sh || return 1
    # sets up fzf alias, not required
    [[ -e $HOME/.alias ]] && source $HOME/.alias
    # sets up z function
    [[ -e $HOME/.function ]] && source $HOME/.function || return 1

    if [[ $(type fzf > /dev/null; echo $?) = 1 ]]; then
        return 1
    fi

    local args="${@:2}"

    (
        z $1

        if [[ $@ = "" ]]; then
            read "dowhat?Do what? "
            args="$dowhat"
        fi
        eval $args
    )
}

if [[ $ZSH_EVAL_CONTEXT != 'toplevel' ]]; then
    # we're sourcing the file, make an alias
    alias in="_in"
else
    # we're running the script, run the command
    _in $*
fi

