.TH USEFUL 7
.\"
.\"
.SH SYNOPSIS
Some commands and other CLI related material that I find useful.
.\"
.\"
.SH COMMANDS
.PP
.BR whois (1)
Internet domain name and network number directory service
.\"
.\"
.SH COMMANDS I'VE DOWNLOADED
.PP
.BR mutt (1)
The Mutt Mail User Agent
.\"
.\"
.SH OTHER SHIT
.PP
.BR sshd_config(5)
OpenSSH SSH daemon configuration file
.PP
.BR \fIhttps://liw.fi/manpages/\fI
The formatting guide for manpages I found
