#! /bin/sh

# Install homebrew
`which ruby` -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# -- cask taps -- {{{
brew tap caskroom/cask
brew tap caskroom/versions
# -- }}}

# -- Brew Packages -- {{{
brew_packages=(
"cmus"
"pipes-sh"
"jmeter"
"figlet"
"universal-ctags/universal-ctags/universal-ctags"
"nginx"
"mysql"
"getantibody/tap/antibody"
"aview"
"findutils"
"cmake"
"toilet"
"node@6"
"tmux"
"fd"
"dialog"
"irssi"
"vegeta"
"rtv"
"hub"
"php@7.1"
"php@7.2"
"nmap"
"composer"
"cmatrix"
"httpie"
"newsboat"
"mycli"
"eddieantonio/eddieantonio/imgcat"
"bat"
"fortune"
"fzf"
"wp-cli"
"shpotify"
"swiftlint"
"reattach-to-user-namespace"
"zsh"
"thefuck"
"rig"
"telnet"
"coreutils"
"pkg-config"
"dnsmasq"
"molovo/revolver/revolver"
"jez/formulae/git-heatmap"
"loadimpact/k6/k6"
"tree"
"luarocks"
"dep"
"python@2"
"rainbarf"
"cowsay"
"spotctl"
"wget"
"mysql@5.6"
# "libiconv" # pre-installed by osx
"vim"
"mutt"
"xcodegen"
"lua"
"lua@5.1"
"nyancat"
"cjbassi/gotop/gotop"
"fswatch"
"screenfetch"
"pv"
"ack"
"neovim"
"jq"
)

# -- }}}

for i in "${brew_packages[@]}"; do
    brew install $i
done
