#! /bin/sh

if test "$USERNAME" = ""; then
    echo "Run export USERNAME first!"
    exit 1
fi

adduser $USERNAME
usermod -aG sudo $USERNAME
su - $USERNAME
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install build-essential curl file git

# -- INSTALL HOMEBREW -- {{{
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
# -- }}}

# -- INSTALL ZSH -- {{{
brew install gcc
apt install zsh
# -- }}}

brew install fortune cowsay figlet toilet

# -- Get antibody -- {{{
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
# -- }}}

curl -sL git.io/antibody | sh -s
chsh -s /usr/bin/zsh $USERNAME

# packages
sudo apt-get install nginx
brew install ack fzf nvim node composer php thefuck
pip3 install pynvim
[[ -e $HOME/.config ]] || mkdir $HOME/.config
[[ -e $HOME/.config/nvim ]] || mkdir $HOME/.config/nvim
[[ -e $HOME/.config/nvim/autoload ]] || mkdir $HOME/.config/nvim/autoload
[[ -e $HOME/.config/nvim/bundle ]] || mkdir $HOME/.config/nvim/bundle
[[ -e $HOME/.config/nvim/colors ]] || mkdir $HOME/.config/nvim/colors
[[ -e $HOME/.config/nvim/autoload/lightline ]] || mkdir $HOME/.config/nvim/autoload/lightline
[[ -e $HOME/.config/nvim/autoload/lightline/colorscheme ]] || mkdir $HOME/.config/nvim/autoload/lightline/colorscheme

git clone https://github.com/VundleVim/Vundle.vim.git ~/.config/nvim/bundle/Vundle.vim
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
