-- init.lua
-- vim: set ts=2 sw=2:
require('xp-bar.plugins.configs.aerial-nvim')
require('xp-bar.plugins.configs.nvim-lint')
require('xp-bar.plugins.configs.nvim-cmp')
require('xp-bar.plugins.configs.fzf-lua')
-- require('xp-bar.plugins.configs.startify')
require('xp-bar.plugins.configs.nerdtree')
require('xp-bar.plugins.configs.gitsigns')
require('xp-bar.plugins.configs.vim-test')
require('xp-bar.plugins.configs.vim-easy-align')
require('xp-bar.plugins.configs.vim-jsdoc')
require('xp-bar.plugins.configs.vim-zoom')
require('xp-bar.plugins.configs.vim-fugitive')
require('xp-bar.plugins.configs.vim-rooter')
require('xp-bar.plugins.configs.emmet-vim')
require('xp-bar.plugins.configs.comment-nvim')
require('xp-bar.plugins.configs.markdown-preview')
require('xp-bar.plugins.configs.pdv')
require('xp-bar.plugins.configs.vim-php-cs-fixer')
require('xp-bar.plugins.configs.lualine')
require('xp-bar.plugins.configs.leap')
require('xp-bar.plugins.configs.zen-mode')
require('xp-bar.plugins.configs.twilight')
require('xp-bar.plugins.configs.navigator-nvim')
require('xp-bar.plugins.configs.mini')
require('xp-bar.plugins.configs.csvview-nvim')
require('xp-bar.plugins.configs.indent-blankline-nvim')
require('xp-bar.plugins.configs.conform-nvim')
require('xp-bar.plugins.configs.alpha-nvim')
