-- init.lua
-- vim: set ts=2 sw=2:
require('xp-bar.plugins.configs.aerial-nvim')
require('xp-bar.plugins.configs.fzf-lua')
require('xp-bar.plugins.configs.vim-tmux-navigator')
require('xp-bar.plugins.configs.startify')
require('xp-bar.plugins.configs.nerdtree')
require('xp-bar.plugins.configs.gitsigns')
require('xp-bar.plugins.configs.vim-test')
require('xp-bar.plugins.configs.vim-easy-align')
require('xp-bar.plugins.configs.goyo')
require('xp-bar.plugins.configs.vim-jsdoc')
require('xp-bar.plugins.configs.vim-zoom')
require('xp-bar.plugins.configs.vim-fugitive')
require('xp-bar.plugins.configs.vim-rooter')
require('xp-bar.plugins.configs.emmet-vim')
require('xp-bar.plugins.configs.commentary')
require('xp-bar.plugins.configs.markdown-preview')
require('xp-bar.plugins.configs.pdv')
require('xp-bar.plugins.configs.vim-php-cs-fixer')
