#!/bin/bash
# NAVIGATION
alias ..="cd ../"
alias ..d="cd $(dirs -v | grep 1 | sed 's/[0-9]*[[:space:]]*//')"
alias l="ls -la1FGH"
alias la="ls -a -FGH"
alias ld="\ls -GHd */"
alias l.="ls -a -GH | grep --color=never '^[\.][^\/\.]'"
alias ll="ls -lh -FGH"
alias lla="ls -lha -FGHll"
alias ls="ls -FGH"
alias mv="mv -v"
alias rm="rm -vi"
alias cp="cp -v"
alias rn="cp"

# GIT
alias main="git checkout main"
alias aa="git add ."
alias ra="git reset"
alias a="git add"
alias ap="git add -p"
alias rp="git reset --patch"
alias an="git add . -N"
alias dis="git diff --staged"
alias stash="git stash"
alias pop="git stash pop"
alias ci="git commit -m"
alias cm="git commit --amend"
alias chp="git cherry-pick"
alias br="git --no-pager branch"
alias mt="git mergetool"
alias fe="git fetch --all"
alias pl="git pull"
alias sw="git switch"
alias glog="nvim -c 'GV' -c 'set foldlevel=1000' -c 'nnoremap q :qa!<cr>'"
alias gfl="git log -p"
alias cisearch="git log -S"
