#!/bin/zsh

local scriptdir=${0:a:h}
local separator=$(echo "\u2007")
local response="$(\
    gh api \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/Jumbleberry/JBX/pulls \
)"
local length="$(jq '. | length' <<< "$response")"
local pulls=$(jq '.[] | {
    title: .title,
    branch: .head.ref,
    base_branch: .base.ref,
    url: .html_url,
    number: .number,
    status: (if .draft == true then "draft" else .state end),
    author: "\(.user.login) (\(.user.html_url))",
    body: .body | @base64,
    labels: [.labels[] | "\(.name) [#\(.color)]"],
    reviewers: [.requested_reviewers[] | "\(.login) (\(.html_url))"]
} | . + {
   labels: .labels | join(","),
   reviewers: .reviewers | join(",")
}' <<< "$response")

local requests=$(jq -r '. | [to_entries[].value] | join("'$separator'")' <<< "$pulls")

echo $requests |\
    fzf \
    -i \
    --delimiter "$separator" \
    --with-nth=1 \
    --nth=1,2,3,5 \
    --preview-window="right,65%" \
    --preview 'echo "\033[34m$(echo {1} | sed "s/^\(.*:\)\(.*\)/$(echo "\033[31m")\1$(echo "\033[34m")\2/g")\033[0m\n\n\033[0mMerging\033[33m "{2}"\033[0m into \033[33m"{3}"\033[0m\n\n""$(echo {8} | base64 --decode | grep -v "<!---" | bat --file-name="\033[34m$(echo {1} | sed "s/^\(.*:\)\(.*\)/$(echo "\033[31m")\1$(echo "\033[34m")\2/g")" --theme=TwoDark --color always -l md)"' \
    --bind 'enter:become(open {4})'
